#!/bin/bash
clear
printf "Build Script written by Francis Nai on 15 May 2019\n"
printf "Email me at francis.nai@sap.com if you have any feedback\n"
printf "####################################################################################################\n"
printf "This script $0 is run by $USER on $OSTYPE with $SHELL at $PWD\n"
printf "Start creating infrastructure assets on Azure on $HOSTNAME\n"
printf "####################################################################################################\n\n"

b="${1,,}"

# Array for Subnet (sub) 
# Column 1 is Subnet Name
# Column 2 is Subnet IP
# Column 3 is Subnet NSG
# Column 4 is NSG Rule Name
# Column 5 is NSG Port
# Column 6 is NSG Priority
# Column 7-9 will be 2nd set of NSG rule
# Column 10-12 will be 3rd set of NSG rule

declare -A sub
num_rows=30
num_columns=9

# Array for Virtual Machine (vlm) 
# Column 1 is Virtual Machine name
# Column 2 is Virtual Machine Image
# Column 3 is Virtual Machine Size
# Column 4 is Virtual Machine Username
# Column 5 is Virtual Machine Password
# Column 6 is Virtual Machine IP
# Column 7 is Virtual Machine FQDN
# Column 8 is Virtual Machine Public IP SKU

declare -A vlm
num_rows=30
num_columns=8


if [ -z "$b" ] || [ -z "$2" ]; then
    printf "Correct Usage:\n"
    printf "$0 <azure resource group> <azure region>\n"
    printf "Example: $0 myResourceGroup 'South East Asia'\n\n"
else
    # Create a resource group.
    printf "\n$2 Azure> $b rg...\n"
    az group create --name $b --location "$2"

    # Create Vnet
    vnetN=my$b
    vnetIP=192.168.0.0/16
    printf "\n$2 Azure> $b rg> $vnetN vnet> $vnetIP...\n\n"
    az network vnet create --name $vnetN --resource-group $b --address-prefixes $vnetIP

    # Create NSG
    sub[1,3]=dmzNSG
    printf "\n$2 Azure> $b rg> $vnetN vnet> $vnetIP> ${sub[1,3]} nsg...\n\n"
    az network nsg create -g $b -n ${sub[1,3]}

    # Create Subnet
    sub[1,1]=DMZ
    sub[1,2]=192.168.5.0/24
    printf "\n$2 Azure> $b rg> $vnetN vnet> $vnetIP> ${sub[1,1]} ${sub[1,2]}> ${sub[1,3]} nsg...\n\n"
    az network vnet subnet create --resource-group $b --vnet-name $vnetN --name ${sub[1,1]} \
        --address-prefixes ${sub[1,2]} --network-security-group ${sub[1,3]}

    # Create NSG rule
    # Turn on Port 22 at NSG
    sub[1,4]=SSH
    sub[1,5]=22
    sub[1,6]=$(( RANDOM % (1000 - 100 + 1 ) + 100 ))
    printf "\n$2 Azure> $b rg> $vnetN vnet> $vnetIP> ${sub[1,1]} ${sub[1,2]}> ${sub[1,3]} nsg> ${sub[1,4]} ${sub[1,5]}> ${sub[1,6]} priority...\n\n"
    az network nsg rule create --name ${sub[1,4]} --nsg-name ${sub[1,3]} --resource-group $b --access Allow \
        --protocol Tcp --direction Inbound --source-address-prefixes '*' --destination-port-ranges ${sub[1,5]} \
        --priority ${sub[1,6]}
    
    # Create VM Linux
    vlm[1,1]=$b"vm"
    vlm[1,2]=ubuntults
    vlm[1,3]=Standard_B1s
    vlm[1,4]=$b"sapuser"
    vlm[1,5]=$b"sap999@333@"
    vlm[1,6]=192.168.5.4
    vlm[1,7]=$b"web"
    vlm[1,8]=Basic

    sed 's/example.com/'${vlm[1,7]}.southeastasia.cloudapp.azure.com'/g' cloud-init-nginx-http-template.txt >> cloud-init-nginx-http.txt

    printf "\n$2 Azure> $b rg> $vnetN vnet> $vnetIP> ${sub[1,1]} ${sub[1,2]}> ${sub[1,3]} nsg> ${sub[1,4]} ${sub[1,5]}> ${sub[1,6]} priority> ${vlm[1,1]} ${vlm[1,2]} ${vlm[1,6]}...\n\n"

    az vm create --name ${vlm[1,1]} \
                --resource-group $b \
                --image ${vlm[1,2]} \
                --size ${vlm[1,3]} \
                --admin-username ${vlm[1,4]} \
                --admin-password ${vlm[1,5]} \
                --authentication-type all \
                --public-ip-address-dns-name ${vlm[1,7]} \
                --public-ip-sku ${vlm[1,8]} \
                --vnet-name $vnetN \
                --private-ip-address ${vlm[1,6]} \
                --subnet ${sub[1,1]} \
                --nsg ${sub[1,3]} \
                --generate-ssh-keys \
                --custom-data cloud-init-nginx-http.txt


    # Create NSG rule
    # Turn on Port 80 at NSG
    sub[1,7]=HTTP
    sub[1,8]=80
    sub[1,9]=$(( RANDOM % (1000 - 100 + 1 ) + 100 ))

    printf "\n$2 Azure> $b rg> $vnetN vnet> $vnetIP> ${sub[1,1]} ${sub[1,2]}> ${sub[1,3]} nsg> ${sub[1,4]} ${sub[1,5]}> ${sub[1,6]} priority> ${vlm[1,1]} ${vlm[1,2]} ${vlm[1,6]}> ${sub[1,7]} ${sub[1,8]}> ${sub[1,9]} priority\n\n"
    az network nsg rule create --name ${sub[1,7]} --nsg-name ${sub[1,3]} --resource-group $b --access Allow \
        --protocol Tcp --direction Inbound --source-address-prefixes '*' --destination-port-ranges ${sub[1,8]} \
        --priority ${sub[1,9]}

    printf "\n"
    az network public-ip show --resource-group $b --name ${vlm[1,1]}PublicIP --query [dnsSettings.fqdn] --output tsv

    rm cloud-init-nginx-http.txt

    printf "\n\n If you like this script, please do not forget to like my post and endorse my skills in Linkedin. Thank you!\n"
    printf " https://www.linkedin.com/in/francis-nai-7454383/  \n\n"
fi
